print("São apenas CRIANÇAS.")
print("Mario  meu fã")
print("Pergunta pro Paulo Guedes")
print("Vai combater o crime com beijinho?")
print("Ta okey?")
print("Aplica a prova do enem pra mim, Dilma e Lula...")
